spring.application.name=30-kunlik

# Server Port (8080 porti band bo'lsa, boshqa portdan foydalanish)
server.port=8082

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/30_kunlik_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect