spring.application.name=30-kunlik

# Render.com PostgreSQL connection
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Fast HikariCP Pool Tuning for Cloud Environments
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

# JPA & Hibernate Performance Tuning
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Boot Startup Optimization
spring.main.banner-mode=off
spring.main.lazy-initialization=true

# Telegram Bot Settings
telegram.bot.username=${TELEGRAM_BOT_USERNAME:testautouz_bot}
telegram.bot.token=${TELEGRAM_BOT_TOKEN:8942004027:AAESyLqIu91HSGwxgiSs8cRVTa9BpJSZgnM}
telegram.bot.admin-id=${TELEGRAM_BOT_ADMIN_ID:8212838308}